### ISSUE TITLE
Milestone 5: My Portfolio Website Deployment.

### ISSUE THREAD

**Issue by BenMKT** [BenMKT/Portfolio#7]
- Deployed my portfolio website earlier using GitHub Pages through this [Link](https://benmkt.github.io/myPortfolio).
- Updated my README to include a link to the online version in the `Live Demo` section.

**Comment by shahadat3669** [comment]
Hi @BenMKT , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Highlights

## Optional suggestions
You can consider:
- [ ] [Optional] Well, your social icons titles look visually good. However, instead of using a `<p>` tag, it would be more semantically appropriate to use a heading tag, such as `<h3>` or `<h4>`, to represent the title. This will improve the structure and accessibility of your code. Please consider updating it accordingly. 👍 
![image](https://github.com/BenMKT/myPortfolio/assets/55840999/ab402212-d600-41d6-8e5c-66b07a84b9b4)
- [ ] [Optional] It appears that you're using the `<h1>` tag for the titles. However, it's recommended to have only one `<h1>` tag per webpage for better accessibility. Consider replacing the `<h1>` tag with an appropriate heading tag, such as `<h2>` to `<h6>`, depending on the hierarchy and relevance of the titles within your code. You can refer to the [documentation on heading elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#accessibility_concerns) for more information. Please 🙏 consider to update your title tag. 👍 
![image](https://github.com/BenMKT/myPortfolio/assets/55840999/d4781785-0c8c-47f6-b9a6-dfe572b9474f)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
